# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/hefftorlinux_4k/stary-night.jpg'

# Special
background='#031525'
foreground='#a7cddd'
cursor='#a7cddd'

# Colors
color0='#031525'
color1='#0470AC'
color2='#546998'
color3='#BA72AD'
color4='#1D91B3'
color5='#5DA2BF'
color6='#23A6C6'
color7='#a7cddd'
color8='#748f9a'
color9='#0470AC'
color10='#546998'
color11='#BA72AD'
color12='#1D91B3'
color13='#5DA2BF'
color14='#23A6C6'
color15='#a7cddd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
