--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/hefftorlinux_4k/stary-night.jpg"

-- Special
background="#031525"
foreground="#a7cddd"
cursor="#a7cddd"

-- Colors
color0="#031525"
color1="#0470AC"
color2="#546998"
color3="#BA72AD"
color4="#1D91B3"
color5="#5DA2BF"
color6="#23A6C6"
color7="#a7cddd"
color8="#748f9a"
color9="#0470AC"
color10="#546998"
color11="#BA72AD"
color12="#1D91B3"
color13="#5DA2BF"
color14="#23A6C6"
color15="#a7cddd"
